TodoListWebApplication/Models/ViewModels/TodoListViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Todo_Domain_Entities;

namespace TodoListWebApplication.Models
{
    public class TodoListViewModel
    {
        public TodoListModel TodoList { get; set; }
        public IEnumerable<TodoModel> Todos { get; set; }
    }
}

TodoListWebApplication/Controllers/TodoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Todo_Domain_Entities;
using Todo_Domain_Entities.Interfaces;
using TodoListWebApplication.Mapper;
using TodoListWebApplication.Models;

namespace TodoListWebApplication.Controllers
{
    public class TodoController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public TodoController(IUnitOfWork unitofWork)
        {
            _unitOfWork = unitofWork;
        }
        // GET: TodoController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var todoEntry = await _unitOfWork.Todo.GetByIDAsync(id);
            return View(todoEntry.TodoDomainClientModel());
        }

        // GET: TodoController/Create/5
        public ActionResult Create(int listID)
        {
            ViewBag.ListID = listID;
            return View();

        }

        // POST: TodoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Create(TodoModel todo)
        {
            try
            {
                await _unitOfWork.Todo.Add(todo.TodoClientToDomainModel());
                _unitOfWork.Complete();

                return RedirectToAction("Details", "TodoLists", new { id = todo.TodoListID });
            }
            catch
            {
                return RedirectToAction(nameof(Error), new { statusCode = StatusCodes.Status404NotFound });
            }
        }

        // GET: TodoController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var todoEntry = await _unitOfWork.Todo.GetByIDAsync(id);

            return View(todoEntry.TodoDomainClientModel());
        }

        // POST: TodoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public RedirectToActionResult Edit(int id, TodoModel todo)
        {
            _unitOfWork.Todo.Update(todo.TodoClientToDomainModel());
            _unitOfWork.Complete();

            return RedirectToAction("Details", "TodoLists", new { id = todo.TodoListID });
        }

        // POST: TodoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Delete(int id)
        {
            var todoEntry = await _unitOfWork.Todo.GetByIDAsync(id);

            await _unitOfWork.Todo.Remove(todoEntry);

            _unitOfWork.Complete();

            return RedirectToAction("Details", "TodoLists", new { id = todoEntry.TodoListID });

        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            return View(new ErrorViewModel { StatusCode = statusCode, RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TodoListWebApplication/Controllers/TodoListsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TodoListWebApplication;
using Todo_Domain_Entities;
using Todo_Domain_Entities.Interfaces;
using TodoListWebApplication.Models;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using System.Text.Json;
using TodoListWebApplication.Mapper;

namespace TodoListWebApplication.Controllers
{
    public class TodoListsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public TodoListsController(IUnitOfWork unitofwork)
        {
            _unitOfWork = unitofwork;
        }

        // GET: TodoListController
        public async Task<ViewResult> Index()
        {
            var todoLists = await _unitOfWork.TodoLists.GetAllAsync();
            _unitOfWork.Complete();

            return View("Index", todoLists.Where(x => !x.IsHidden).ListOfTodoListsDomainToClientModel());
        }

        // GET: TodoListController
        public async Task<ViewResult> HiddenLists()
        {
            var todoLists = await _unitOfWork.TodoLists.GetAllAsync();
            _unitOfWork.Complete();

            return View("Index", todoLists.Where(x => x.IsHidden).ListOfTodoListsDomainToClientModel());
        }
        // GET: TodoLists/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var todoList = await _unitOfWork.TodoLists.GetTodoListsWithTodosAsync(id);

            return View(new TodoListViewModel()
            {
                TodoList = todoList.TodoListDomainToClientModel(),
                Todos = todoList.Todos.ListOfTodosDomainToClientModel(),
            });
        }

        // GET: TodoLists/Create
        public ViewResult Create()
        {
            return View();
        }

        // POST: TodoLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<RedirectToActionResult> Create(TodoListModel todoList)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Error));
            }

            await _unitOfWork.TodoLists.Add(todoList.TodoListClientToDomainModel());
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        // GET: TodoLists/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var todoList = await _unitOfWork.TodoLists.GetByIDAsync(id);

            return View(todoList.TodoListDomainToClientModel());
        }

        // POST: TodoLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public  RedirectToActionResult Edit(int id,  TodoListModel todoList)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction(nameof(Error), new { statusCode = StatusCodes.Status406NotAcceptable });
            }

            _unitOfWork.TodoLists.Update(todoList.TodoListClientToDomainModel());
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));
        }

        // POST: TodoLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var todoList = await _unitOfWork.TodoLists.GetByIDAsync(id);
            var todos = await _unitOfWork.Todo.GetTodosForTodoListWithID(id);
            _unitOfWork.Todo.RemoveRange(todos);
            await _unitOfWork.TodoLists.Remove(todoList);
            _unitOfWork.Complete();

            return RedirectToAction(nameof(Index));

        }
        [HttpGet]
        public async Task<IActionResult> Copy(int id)
        {
            var todoList = await _unitOfWork.TodoLists.GetTodoListsWithTodosAsync(id);

            var jsonTodoList = JsonSerializer.Serialize(todoList.TodoListDomainToClientModel());
            var jsonTodoEntries = from todo in todoList.Todos.ListOfTodosDomainToClientModel()
                                  select JsonSerializer.Serialize(todo);

            return View(nameof(Copy), new JsonTodoViewModel { JsonTodoList = jsonTodoList, JsonTodos = jsonTodoEntries });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            return View(new ErrorViewModel { StatusCode = statusCode, RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TodoListWebApplication/Views/TodoLists/Copy.cshtml
@model JsonTodoViewModel
@{
    Layout = "";

}
<div>

    <h3>@Model.JsonTodoList</h3>

    @foreach (var todo in Model.JsonTodos)
    {
        <h5>@todo</h5>
    }
</div>

<a asp-controller="TodoLists" asp-action="Index">Back</a>

TodoListWebApplication/Views/TodoLists/Create.cshtml
@model TodoListModel

<form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="TodoLists">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="text-light">
        <div class="form-group">
            <h3>Create New Todo List</h3>
        </div>
        <div class="form-group text-light">
            <label asp-for="ListName">Todo List Name</label>
            <input asp-for="ListName" class="form-control" required />
            <span asp-validation-for="ListName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="IsHidden"></label>
            <input asp-for="IsHidden" type="checkbox" />
        </div>

        <div class="form-group">
            <input type="submit" value="Add" class="btn btn-primary bg-dark btn-outline-light text-light font-weight-bold m-1" />
            <a class="btn btn-info btn-sm pull-right float-right m-1" asp-controller="TodoLists" asp-action="Index">Back</a>
        </div>
    </div>
</form>

TodoListWebApplication/Views/TodoLists/Details.cshtml
@model TodoListViewModel

<div class="card border-0 bg-dark text-white m-1 p-1">
    <h3 class="card-title display-4">Title: @Model.TodoList.ListName</h3>
    <div class="bg-faded p-1">
    </div>
    <div class="bg-faded p-1">
        <h4>
            Creation Time: @Model.TodoList.CreationTime
        </h4>
    </div>
    <div class="bg-faded p-1">
        <h4>
            IsHidden : @Model.TodoList.IsHidden
        </h4>
    </div>
    <div class="m-2 p-1">
        <a class="btn btn-primary bg-dark btn-outline-light text-light font-weight-bold float-left m-1" asp-controller="Todo" asp-action="Create" asp-route-listid="@Model.TodoList.ID">Add Todo</a>
        <form method="post" enctype="multipart/form-data" asp-controller="TodoLists" asp-action="Delete" asp-route-id="@Model.TodoList.ID">
            <input type="submit" onclick="return confirm('Item will be deleted.')" value="Delete" class="btn bg-danger btn-outline-light text-light font-weight-bold float-right m-1" />
        </form>
        <a class="btn btn-secondary btn-outline-light font-weight-bold float-right m-1" asp-controller="TodoLists" asp-action="Index">Back</a>
        <a class="btn btn-outline-light float-right font-weight-bold m-1" asp-controller="TodoLists" asp-action="Edit" asp-route-id="@Model.TodoList.ID">Edit</a>
    </div>
    <h3> Todo's</h3>
    @foreach (var item in Model.Todos)
    {
        <partial name="TodoView" model="item" />
    }
</div>

TodoListWebApplication/Views/TodoLists/Edit.cshtml
@model TodoListModel

@{
    ViewData["Title"] = "Edit";
}
<div class="container text-light">
    <h1>Edit</h1>

    <h4>Todo List</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ID" />
                <div class="form-group">
                    <label asp-for="ListName" class="control-label"></label>
                    <input asp-for="ListName" class="form-control" />
                    <span asp-validation-for="ListName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IsHidden"></label>
                    <input type="checkbox" asp-for="IsHidden" />
                </div>
                <div class="form-group">
                    <label asp-for="CreationTime" class="control-label"></label>
                    <input asp-for="CreationTime" class="form-control" />
                    <span asp-validation-for="CreationTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-dark text-light font-weight-bold btn-outline-light float-left m-1" />
                </div>
            </form>
        </div>
    </div>
    <a class="btn btn-info btn-sm pull-right float-right m-1" asp-controller="TodoLists" asp-action="Details" asp-route-id="@Model.ID">
        Back
    </a>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TodoListWebApplication/Views/TodoLists/Index.cshtml
@model IEnumerable<TodoListModel>
<div class="bg-dark text-white">
    <h1> Todo Lists</h1>
    <div class="m-1 p-1">
    </div>
    <div class="card border-0 m-1 p-1 bg-dark">

        @foreach (var m in Model)
            {
        <partial name="TodoListView" model="m" />
            }
        
        <div class="m-1 p-1">
            <a class="btn btn-primary bg-dark btn-outline-light text-light font-weight-bold float-right m-1" asp-controller="TodoLists" asp-action="Create">Create new</a>
        </div>
    </div>
</div>